---
name: docker-ansible-ol Build

on:
  pull_request:
  push:
    branches:
      - "main"
  schedule:
    - cron: "00 0 * * 0"

jobs:
  ol8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Test building images
        run: scripts/build.sh 8 8.6

      - name: Run one of the built image.
        run: docker run --name bmeme-docker-ansible-ol -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro bmeme/docker-ansible-ol:8

      - name: Verify Ansible is accessible
        run: docker exec --tty bmeme-docker-ansible-ol env TERM=xterm ansible --version
